const relativePathToImagesDir = '../../assets/media/avatars/'

export const IMAGES = {
    //png
    1  : require(relativePathToImagesDir +  1 + '.png'),
    2  : require(relativePathToImagesDir +  2 + '.png'),
    3  : require(relativePathToImagesDir +  3 + '.png'),
    4  : require(relativePathToImagesDir +  4 + '.png'),
    5  : require(relativePathToImagesDir +  5 + '.png'),
    6  : require(relativePathToImagesDir +  6 + '.png'),
    7  : require(relativePathToImagesDir +  7 + '.png'),
    8  : require(relativePathToImagesDir +  8 + '.png'),
    9  : require(relativePathToImagesDir +  9 + '.png'),
    10 : require(relativePathToImagesDir + 10 + '.png'),
    11 : require(relativePathToImagesDir + 11 + '.png'),
    12 : require(relativePathToImagesDir + 12 + '.png'),
    13 : require(relativePathToImagesDir + 13 + '.png'),
    14 : require(relativePathToImagesDir + 14 + '.png'),
    15 : require(relativePathToImagesDir + 15 + '.png'),
    16 : require(relativePathToImagesDir + 16 + '.png'),
    17 : require(relativePathToImagesDir + 17 + '.png'),
    18 : require(relativePathToImagesDir + 18 + '.png'),
    19 : require(relativePathToImagesDir + 19 + '.png'),
    20 : require(relativePathToImagesDir + 20 + '.png'),

    // jpg
    21 : require(relativePathToImagesDir + 21 + '.jpg'),
    22 : require(relativePathToImagesDir + 22 + '.jpg'),
    23 : require(relativePathToImagesDir + 23 + '.jpg'),
    24 : require(relativePathToImagesDir + 24 + '.jpg'),
    25 : require(relativePathToImagesDir + 25 + '.jpg'),
    26 : require(relativePathToImagesDir + 26 + '.jpg'),
    27 : require(relativePathToImagesDir + 27 + '.jpg'),
    28 : require(relativePathToImagesDir + 28 + '.jpg'),
    29 : require(relativePathToImagesDir + 29 + '.jpg'),
    30 : require(relativePathToImagesDir + 30 + '.jpg'),
    31 : require(relativePathToImagesDir + 31 + '.jpg'),
    32 : require(relativePathToImagesDir + 32 + '.jpg'),
    33 : require(relativePathToImagesDir + 33 + '.jpg'),
    34 : require(relativePathToImagesDir + 34 + '.jpg'),
    35 : require(relativePathToImagesDir + 35 + '.jpg'),
    36 : require(relativePathToImagesDir + 36 + '.jpg'),
    37 : require(relativePathToImagesDir + 37 + '.jpg'),
    38 : require(relativePathToImagesDir + 38 + '.jpg'),
}